### PR TITLE
updated default.nix

### PR DESCRIPTION
**Pull request by GildedSeraphim**
changed fetchFromGithub -> fetchFromGitHub to avoid build errors

### CODE REVIEW

**Comment by Eveeifyeve** [comment]
Hey I have noticed they are the same thing when I did a find in my browser it shows up as same. 
So I see no difference in this pr, maybe you forgot to push changes or something @GildedSeraphim?

**Review by Eveeifyeve — CHANGES_REQUESTED** [review]
No difference between your changes.

**Comment by Gliczy** [comment]
The 'h' in `fetchFromGitHub` was lowercase, they capitalized it.

**Comment by Eveeifyeve** [comment]
Next time, please make an issue.

**Pull request closed without merging**
